services:
  - type: web
    name: chatapp-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MONGODB_URI
        value: your_connection_string_here
    rootDir: backend  # change this if your backend is not in a folder
